# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'syskit/pocolog/version'

Gem::Specification.new do |spec|
  spec.name          = "syskit-pocolog"
  spec.version       = Syskit::Pocolog::VERSION
  spec.authors       = ["Sylvain Joyeux"]
  spec.email         = ["sylvain.joyeux@m4x.org"]

  spec.summary       = "A Syskit plugin that allows to replay log files generated by pocolog"
  spec.description   = "Adds the APIs necessary to transform component networks to replay log files"
  spec.homepage      = "https://github.com/rock-core/syskit-pocolog"
  spec.license       = "MIT"

  spec.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  spec.bindir        = "exe"
  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]

  spec.add_dependency 'syskit'
  spec.add_dependency 'metaruby'
  spec.add_development_dependency "bundler", "~> 1.11"
  spec.add_development_dependency "rake", "~> 10.0"
  spec.add_development_dependency "minitest", "~> 5.0"
end
